'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'react-date-picker/dist/DatePicker.css';
import 'react-calendar/dist/Calendar.css';
import { createContext, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const ReportContext = createContext<any>(null)

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [ reportByTraineesData, setReportByTraineesData ] = useState<any>([])
  const [ reportByCoursesData, setReportByCoursesData ] = useState<any>([])

  const reportContextValue: any = {
    reportByTraineesData,
    setReportByTraineesData,
    reportByCoursesData,
    setReportByCoursesData,
  };


  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <ReportContext.Provider value={reportContextValue}>
          {children}
        </ReportContext.Provider>
      </body>
    </html>
  );
}
